name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple-deployment-pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5001
      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ github.event_name == 'push' }}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: ${{ github.event_name == 'push' }}
      - name: discord success notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() && github.event_name == 'push'}}
        env:
          LAST_COMMIT_AUTHOR: ${{ toJSon(github.event.head_commit.author.username) }}
        with:
          severity: info
          description: A new version of Pokedex deployed!
          webhookURL: ${{ secrets.DISCORD_WEBHOOK }}
          details: to https://full-stack-open-pokedex-thiom.fly.dev/ by ${{ fromJSON(env.LAST_COMMIT_AUTHOR) }}
      - name: discord failure notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        env:
          LAST_COMMIT_AUTHOR: ${{ toJSon(github.event.head_commit.author.username) }}
          LAST_COMMIT_URL: ${{ toJson(github.event.head_commit.url) }}
        with:
          severity: error
          description: Build failed!
          webhookURL: ${{ secrets.DISCORD_WEBHOOK }}
          details: commit ${{ fromJSON(env.LAST_COMMIT_URL) }} by ${{ fromJSON(env.LAST_COMMIT_AUTHOR) }} broke the build
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(toJSon(github.event.commits.*.message)), 'skip') }}
    needs: [simple-deployment-pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
